[package]
name = "splitt"
description = "Split text in your terminal"
version = "0.1.0"
edition = "2024"
license = "MIT"
license-file = "LICENSE"
repository = "https://github.com/6km/splitt"
readme = "README.md"

[dependencies]
clap = {version="4.5.34", features=["derive"]}